defaultContentlanguage : "en"
title: "ZOU Foling's Homepage" # <img src="./photo.jpg" alt="Name" height="250">"

     
theme: "PaperMod"

markup.goldmark.renderer:
  unsafe: true 

params:
  mainSections:
       
  math: true
  ## code
  ShowCodeCopyButtons: true

  ## toc
  showtoc: false
  tocopen: false
  UseHugoToc: false

  ## additional info
  # ShowPostNavLinks: true
  # ShowWordCount: true
  # ShowReadingTime: true

  ## layout
  # ShowBreadCrumbs: true
  hideSummary: true

  ## use chroma for markup
  assets:
    disableHLJS: true

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1

## use chroma for syntax highlighting
markup:
  highlight:
    # anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: true
    # noClasses: false
    style: monokai
